"""Keywords value object for academic papers.

Represents a collection of keywords with validation, normalization,
and deduplication.
"""

from collections.abc import Iterator
from dataclasses import dataclass

from lit_review.domain.exceptions import ValidationError


@dataclass(frozen=True)
class Keywords:
    """Immutable keywords collection with normalization and deduplication.

    Keywords are automatically:
    - Converted to lowercase for consistency
    - Stripped of leading/trailing whitespace
    - Deduplicated (case-insensitive)
    - Validated to ensure no empty terms

    Attributes:
        terms: Tuple of validated, normalized keyword strings.

    Raises:
        ValidationError: If keywords list is empty or contains empty terms.

    Example:
        >>> keywords = Keywords(["Machine Learning", "healthcare", "AI"])
        >>> keywords.terms
        ('machine learning', 'healthcare', 'ai')
        >>> "machine learning" in keywords
        True
    """

    terms: tuple[str, ...]

    def __init__(self, keywords: list[str]) -> None:
        """Initialize Keywords with validation and normalization.

        Args:
            keywords: List of keyword strings.

        Raises:
            ValidationError: If keywords list is empty or contains empty terms.
        """
        if not keywords:
            raise ValidationError("Keywords list cannot be empty")

        # Normalize: strip whitespace and convert to lowercase
        normalized = [kw.strip().lower() for kw in keywords]

        # Validate: no empty strings after normalization
        if any(not kw for kw in normalized):
            raise ValidationError("Keywords cannot be empty")

        # Deduplicate while preserving order (first occurrence wins)
        seen: set[str] = set()
        deduplicated = []
        for kw in normalized:
            if kw not in seen:
                seen.add(kw)
                deduplicated.append(kw)

        # Use object.__setattr__ to bypass frozen dataclass restriction
        object.__setattr__(self, "terms", tuple(deduplicated))

    def __str__(self) -> str:
        """Return keywords as comma-separated string.

        Returns:
            Comma-separated keyword string.

        Example:
            >>> str(Keywords(["machine", "learning"]))
            'machine, learning'
        """
        return ", ".join(self.terms)

    def __len__(self) -> int:
        """Return number of keywords.

        Returns:
            Count of keywords.

        Example:
            >>> len(Keywords(["machine", "learning"]))
            2
        """
        return len(self.terms)

    def __contains__(self, keyword: str) -> bool:
        """Check if keyword exists in collection (case-insensitive).

        Args:
            keyword: Keyword to search for.

        Returns:
            True if keyword exists in collection.

        Example:
            >>> keywords = Keywords(["Machine Learning"])
            >>> "machine learning" in keywords
            True
        """
        return keyword.lower() in self.terms

    def __iter__(self) -> Iterator[str]:
        """Return iterator over keywords.

        Returns:
            Iterator of keyword strings.

        Example:
            >>> list(Keywords(["machine", "learning"]))
            ['machine', 'learning']
        """
        return iter(self.terms)

    def __getitem__(self, index: int) -> str:
        """Get keyword by index.

        Args:
            index: Index of keyword (supports negative indexing).

        Returns:
            Keyword at specified index.

        Raises:
            IndexError: If index is out of range.

        Example:
            >>> keywords = Keywords(["machine", "learning"])
            >>> keywords[0]
            'machine'
            >>> keywords[-1]
            'learning'
        """
        return self.terms[index]

    def to_list(self) -> list[str]:
        """Return keywords as a mutable list copy.

        Returns:
            List copy of keywords.

        Example:
            >>> keywords = Keywords(["machine", "learning"])
            >>> keywords.to_list()
            ['machine', 'learning']
        """
        return list(self.terms)

    # Note: __eq__ and __hash__ are auto-generated by @dataclass(frozen=True)
    # based on the 'terms' field. No need to override them.
